spring:
  application:
    name: log-service-center-gateway
  profiles:
    active: default
eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
    ip-address: 192.168.1.150
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.1.150:10100/eureka/
logging:
  config: classpath:logback.xml
server:
  port: 10300