spring:
  application:
    name: gateway
  profiles:
    active: test
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
#    hostname: log.yunyichina.cn
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://120.77.59.164:10100/eureka/
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
server:
  port: 10300