spring:
  application:
    name: log-service-center-gateway
  profiles:
    active: default
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
server:
  port: 10300
logging:
  config: classpath:logback.xml