spring:
  application:
    name: searcher-shensan
  profiles:
    active: dev
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://120.77.59.164:10100/eureka/
logging:
  config: classpath:logback/logback-test.xml
#
constants:
  upload:
#    logSuffix: .log
#    indexSuffix: .index
#    bakSuffix: .bak
#    zipIndex: .zip
    logRootDir: D://log//logRootDir
    indexRootDir: D://log//indexRootDir
server:
  port: 10500
