spring:
  application:
    name: searcher-node
  profiles:
    active: dev,extra
  cloud:
    config:
      enabled: true
      discovery:
        serviceId: config-center
        enabled: true
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
logging:
  config: classpath:logback.xml
