spring:
  application:
    name: searcher-shensan-test
  profiles:
    active: test
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
logging:
  config: classpath:logback/logback-test.xml
#
constants:
  upload:
    logRootDir: D://log//logRootDir
    indexRootDir: D://log//indexRootDir
server:
  port: 10500
endpoints:
  cors:
    allowed-origins: http://localhost,http://127.0.0.1
    allowed-methods: GET,POST
