spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/log_system?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: admin
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: api
  profiles:
    active: test
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    hostname: log.yunyichina.cn
logging:
  config: classpath:logback/logback-test.xml
server:
  port: 10600
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
endpoints:
  cors:
    allowed-origins: http://localhost,http://127.0.0.1
    allowed-methods: GET,POST