spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/log_system?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: api
  profiles:
    active: default
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://120.77.59.164:10100/eureka/
logging:
  config: classpath:logback.xml
server:
  context-path: /api
  port: 10700
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml