spring:
  application:
    name: searcher-gateway
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: config-center
  profiles:
    active: dev,extra
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
logging:
  config: classpath:logback-${spring.profiles.active}.xml
endpoints:
  health:
    enabled: true
