spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/log_system?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: searcher-gateway
  profiles:
    active: test
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
logging:
  config: classpath:logback/logback-test.xml
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 10403

