spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: file:///D:/gitRepo/gitHub/log-sys/log-resource/config
  application:
    name: log-service-center-config-center
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka/
  instance:
    hostname: localhost
server:
  port: 10200
logging:
  config: classpath:logback.xml