spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/gitRepo/gitHub/log-sys/log-resource/config-repo
      username: test
      password: test
  application:
    name: config-center
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4
server:
  port: 10200
logging:
  config: classpath:logback.xml