spring:
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: file:///D:/gitRepo/yunyi/src/log/log-sys/log-resource/config-repo
          username: test
          password: test
  application:
    name: log-service-center-config-center
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://192.168.1.150:10100/eureka/
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
    ip-address: 192.168.1.150
    instance-id: ${eureka.instance.ip-address}:${server.port}
server:
  port: 10200
logging:
  config: classpath:logback.xml