spring:
  application:
    name: log-service-center-config-center
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: file:///D:/gitRepo/gitHub/log-sys/log-resource/config
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10100/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
server:
  port: 10200
logging:
  config: classpath:logback.xml