eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
spring:
  application:
    name: reverse-proxy
server:
  port: 10200
zuul:
  routes:
    collector-gateway: ${service.route.collector-gateway}/**
    searcher-gateway: ${service.route.searcher-gateway}/**
service:
  route:
    collector-gateway: /collector/gateway
    searcher-gateway: /searcher/gateway
