server:
  port: 10600
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${random.value}
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/log_system?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 3
      min-idle: 100
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: false
      test-on-return: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
endpoints:
  cors:
    allowed-origins: http://localhost:8080
    allowed-methods: GET,POST