#Server Configuration
server:
  port: 9999
  context-path: /
  ssl:
    key-store: classpath:.keystore
    key-store-password: 123123
    key-alias: tomcat

#Logback Configuration
logging:
  config: classpath:logback/logback.xml


#spring Configuration 目前只有一个配置文件,如果有需要,可以分为dev和prod,然后再通过spring.profiles.active=prod 来切换生产或开发环境的配置文件.
spring:
#  cache:
#    ehcache:
#      config: classpath:ehcache.xml
  datasource:
    #***+++++++++++注意+++++++++++***,由于为了更精简配置,当更新datasoruce的url,username,password,driver-class-name的时候,还要改logback.xml的dbAppender的datasource的配置.
    url: jdbc:mysql://120.76.230.134:3306/front_shensan?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false #注意!
    username: yunyi
    password: yunyi2016
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initial-size: 3
      min-idle: 100
      max-active: 300
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: false
      test-on-return: false


# Mybatis Configuration
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml


#His Properties
his:
  url: http://113.98.232.21:8000/HealDoc.asmx?wsdl


#调度中心签名相关
sign:
  key: 02af49858e6a4cdeb4ebe9aac8656b4b
  validated: false