spring:
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
server:
  port: 10200