spring:
  application:
    name: reverse-proxy
  profiles:
    active: dev,extra
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-center
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
    healthcheck:
      enabled: true
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
