eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
spring:
  application:
    name: gateway
server:
  port: 10300
zuul:
  routes:
    log-center: /log/center/**
    collection-node: /collection/node/**

