var:
  tag: shensan
  env: test
  profiles:
    active: ${var.env}
logging:
  config: classpath:logback/logback-test.xml
#
fixedRate: 120000
dir:
  logRoot: /data/front/shensan/yylog
  tmpZip: /data/log-sys/collector/${var.env}/${var.tag}/cache/tmpZip
url:
  gateway: http://127.0.0.1:10300
  uploadServer: ${url.gateway}/searcher-${var.tag}-${var.env}/file/upload
  tagSet: ${url.gateway}/api/collector/tag/${spring.application.name}
path:
  properties: /data/log-sys/collector/${var.env}/${var.tag}/cache/cache.properties
server:
  port: 10800

configDir:
  collectorMap:
    shensan:
      logRootDir: F:${file.separator}log${file.separator}data${file.separator}front${file.separator}shensan${file.separator}yylog
      tmpZipDir: F:${file.separator}log${file.separator}data${file.separator}logSys${file.separator}collector${file.separator}shensan${file.separator}other${file.separator}tmpZip
      gateway: http://127.0.0.1:10300
      uploadServerUrl: http://127.0.0.1:10300/searcher/file/upload/v2
      tagSet: http://127.0.0.1:10300/api/collector/tag/shensan
      propertiesPath: F:${file.separator}log${file.separator}data${file.separator}logSys${file.separator}collector${file.separator}shensan${file.separator}other${file.separator}cache.properties
      fixedRate: 120000
    beida:
      logRootDir: F:${file.separator}log${file.separator}data${file.separator}front${file.separator}shensan${file.separator}yylog
      tmpZipDir: F:${file.separator}log${file.separator}data${file.separator}logSys${file.separator}collector${file.separator}beida${file.separator}other${file.separator}tmpZip
      gateway: http://127.0.0.1:10300
      uploadServerUrl: http://127.0.0.1:10300/searcher/file/upload/v2
      tagSet: http://127.0.0.1:10300/api/collector/tag/beida
      propertiesPath: F:${file.separator}log${file.separator}data${file.separator}logSys${file.separator}collector${file.separator}beida${file.separator}other${file.separator}cache.properties
      fixedRate: 120000
    shener:
      logRootDir: F:${file.separator}log${file.separator}data${file.separator}front${file.separator}shensan${file.separator}yylog
      tmpZipDir: F:${file.separator}log${file.separator}data${file.separator}logSys${file.separator}collector${file.separator}shener${file.separator}other${file.separator}tmpZip
      gateway: http://127.0.0.1:10300
      uploadServerUrl: http://127.0.0.1:10300/searcher/file/upload/v2
      tagSet: http://127.0.0.1:10300/api/collector/tag/collector-shener
      propertiesPath: F:${file.separator}log${file.separator}data${file.separator}logSys${file.separator}collector${file.separator}shener${file.separator}other${file.separator}cache.properties
      fixedRate: 120000
