logging:
  config: classpath:logback.xml
server:
  port: 10600
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.yunyichina.log.common.entity.entity.do_
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/log_system?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}
    hostname: log.yunyichina.cn
