eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
      ip-address: 127.0.0.1
      prefer-ip-address: true
#      hostname: log.yunyichina.cn
spring:
  profiles:
    active: test
server:
  port: 10100
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml