spring:
  application:
    name: log-center
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        serviceId: config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/
server:
  port: 10400
