spring:
  application:
    name: schedule-task

filePath:
# 记录时间的游标路径
  cursorPropPath: E:\zTest\cursor.properties
# 记录上传因某种原因失败的日志集合路径
  filesPropPath: E:\zTest\files.properties
# 日志的根目录
  logPath: "E:\\zTest\\testLog1";
# 压缩上传文件的临时zip目录
  uploadfilePath: E:\zTest\testLog.zip

constant:
# 游标的key值
  cursorKey: cursor_key
