eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    instance-id: ${eureka.instance.ipAddress}:${server.port}
    prefer-ip-address: true
    ipAddress: 127.0.0.1 #必须提供ip
logging:
  config: classpath:logback.xml
server:
  port: 10402
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
spring:
  redis:
    host: 192.168.1.168
    password: 123