eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
spring:
  profiles:
    active: default
server:
  port: 10100
logging:
  config: classpath:logback.xml