spring:
  application:
    name: gateway
  profiles:
    active: test
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
server:
  port: 10300