var:
  tag: shensan
  env: test
spring:
  application:
    name: collector-${var.tag}-${var.env}
  profiles:
    active: ${var.env}
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    hostname: log.yunyichina.cn
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
logging:
  config: classpath:logback/logback-test.xml
#
fixedRate: 120000
dir:
  logRoot: /data/front/shensan/yylog
  tmpZip: /data/log-sys/collector/${var.env}/${var.tag}/cache/tmpZip
url:
  gateway: http://127.0.0.1:10300
  uploadServer: ${url.gateway}/searcher-${var.tag}-${var.env}/file/upload
  tagSet: ${url.gateway}/api/collector/tag/${spring.application.name}
path:
  properties: /data/log-sys/collector/${var.env}/${var.tag}/cache/cache.properties
server:
  port: 10800
