spring:
  application:
    name: collector-shensan
  profiles:
    active: test
eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/
logging:
  config: classpath:logback/logback-test.xml
#
cron: 0/5 * *  * * ?
fixedRate: 300000
dir:
  logRoot: D:${file.separator}logRoot
  tmpZip: D:${file.separator}tmpZip
url:
  uploadServer: http://192.168.1.150:10300/searcher-node/file/upload
path:
  properties: D:${file.separator}1.properties
server:
  port: 10600
